spring:
  datasource:
    url: jdbc:mysql://tryeat-db.cgqd8n6rxvm9.ap-northeast-2.rds.amazonaws.com:3306/tryeat_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: tryeatAdmin
    password: rlaDOSrla+969798
    driver-class-name: com.mysql.cj.jdbc.Driver

  output:
    ansi:
      enabled: always
  jpa:
    open-in-view: false
    hibernate:
      format_sql: true

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
    org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket: tryeat.bucket
    credentials:
      access-key: AKIAQVELX6TOS4S4XFJX
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false